services:
  - type: web
    name: codelyn-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18"
